import Navbar from '@/components/navbar'
import FooterSimple from '@/components/footerSimple'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | Amona',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#faf8f5] font-sans text-slate-900">
      <Navbar />
      <main className="mx-auto max-w-[760px] px-5 py-12 sm:py-16">
        <h1 className="text-3xl font-bold tracking-tight text-[#221810] mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-[#9A7360] mb-10">
          Last updated: April 2026
        </p>

        <div className="prose prose-slate prose-sm max-w-none space-y-8 text-[15px] leading-[1.8] text-[#4a3f38]">
          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Amona platform ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. Amona is an itinerary generation and travel community platform — we do not operate as a travel agency or tour operator.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">2. Description of Service</h2>
            <p>
              Amona provides AI-powered travel itinerary generation, a community-driven marketplace for sharing travel packages, travel guides, and social features for experience sharing. The platform facilitates planning and community connection but does not provide on-ground travel services, bookings, or guarantees.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">3. User Accounts</h2>
            <p>
              To access certain features, you must create an account with accurate and complete information. You are responsible for maintaining the confidentiality of your credentials and all activities under your account. You must be at least 16 years old to create an account. You agree to notify us immediately of any unauthorized use.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">4. User Content</h2>
            <p>
              You retain ownership of content you post (photos, reviews, itineraries, comments). By posting content, you grant Amona a non-exclusive, worldwide, royalty-free license to display, distribute, and promote your content within the platform. You are solely responsible for the content you share and must not post content that is illegal, harmful, misleading, or infringes on third-party rights.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">5. AI-Generated Content</h2>
            <p>
              Itineraries and recommendations generated by our AI are suggestions only. They may contain inaccuracies regarding pricing, availability, safety conditions, or visa requirements. Always verify critical travel information with official sources. Amona is not liable for decisions made based on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">6. Marketplace & Packages</h2>
            <p>
              Packages shared on the marketplace are user-generated content. Amona does not verify, endorse, or guarantee the accuracy of any package listing. Any transactions, arrangements, or communications between users are solely between those parties. Amona is not responsible for the quality, safety, or legality of listed packages.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">7. Prohibited Conduct</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1.5 mt-2">
              <li>Use the Service for any illegal or unauthorized purpose</li>
              <li>Post false, misleading, or fraudulent travel information</li>
              <li>Harass, abuse, or harm other users</li>
              <li>Attempt to gain unauthorized access to other accounts or systems</li>
              <li>Scrape, crawl, or use automated means to access the Service without permission</li>
              <li>Impersonate another person or entity</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">8. Limitation of Liability</h2>
            <p>
              Amona is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform. Our total liability is limited to the amount you paid to use the Service (if any). We do not guarantee uninterrupted or error-free operation.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">9. Termination</h2>
            <p>
              We may suspend or terminate your account at any time for violation of these terms or for any reason at our discretion. You may delete your account at any time through your profile settings. Upon termination, your right to use the Service ceases, but provisions that by nature should survive will remain in effect.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">10. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance. We will notify users of material changes via email or platform notification.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[#221810] mb-3">11. Contact</h2>
            <p>
              For questions about these terms, contact us at <span className="font-semibold text-primary">support@amona.travel</span>.
            </p>
          </section>
        </div>
      </main>
      <FooterSimple />
    </div>
  )
}
