import { PackageCardData, CommunityPostData } from "@/types/homepage";

export const topRatedPackages: PackageCardData[] = [
    {
        id: "serengeti-safari",
        title: "Serengeti Safari",
        location: "Tanzania",
        image: "/homepage/top_rated3.png",
        rating: 4.8,
        reviewCount: 245,
        price: 2400,
        currency: "$",
        duration: "7 Days",
        category: "Safari",
        groupSize: "Family",
    },
    {
        id: "cape-town-coastal",
        title: "Cape Town Coastal",
        location: "South Africa",
        image: "/homepage/top_rated2.png",
        rating: 4.7,
        reviewCount: 189,
        price: 1899,
        currency: "$",
        duration: "5 Days",
        category: "Coastal",
        groupSize: "Couples",
    },
    {
        id: "victoria-falls-expedition",
        title: "Victoria Falls Expedition",
        location: "Zimbabwe",
        image: "/homepage/top_rated1.png",
        rating: 4.9,
        reviewCount: 312,
        price: 1350,
        currency: "$",
        duration: "4 Days",
        category: "Adventure",
        groupSize: "Group",
    },
    {
        id: "okavango-delta-explorer",
        title: "Okavango Delta Explorer",
        location: "Botswana",
        image: "/homepage/top_rated3.png",
        rating: 4.9,
        reviewCount: 156,
        price: 3200,
        currency: "$",
        duration: "6 Days",
        category: "Safari",
        groupSize: "Couples",
    },
    {
        id: "marrakech-medina-tour",
        title: "Marrakech Medina Tour",
        location: "Morocco",
        image: "/homepage/top_rated2.png",
        rating: 4.6,
        reviewCount: 420,
        price: 850,
        currency: "$",
        duration: "3 Days",
        category: "Culture",
        groupSize: "Group",
    },
    {
        id: "mount-kilimanjaro-trek",
        title: "Mount Kilimanjaro Trek",
        location: "Tanzania",
        image: "/homepage/top_rated1.png",
        rating: 4.8,
        reviewCount: 278,
        price: 2100,
        currency: "$",
        duration: "8 Days",
        category: "Adventure",
        groupSize: "Group",
    },
];

export const communityPosts: CommunityPostData[] = [
    {
        id: "post-1",
        author: {
            name: "Sarah Jenkins",
            avatar: "/homepage/community3.png",
        },
        timeAgo: "2 hours ago",
        image: "/homepage/community3.png",
        description:
            "Unreal experience spotting this beauty on our morning drive in Chobe National Park. Truly breathtaking!",
        likes: 1200,
        comments: 42,
        shares: 45,
    },
    {
        id: "post-2",
        author: {
            name: "Marcus Chen",
            avatar: "/homepage/community2.png",
        },
        timeAgo: "Yesterday",
        image: "/homepage/community2.png",
        description:
            "Learning about Masai traditions was the highlight of our trip. Such a rich and welcoming culture.",
        likes: 856,
        comments: 12,
        shares: 67,
    },
    {
        id: "post-3",
        author: {
            name: "Elena Rodriguez",
            avatar: "/homepage/community1.png",
        },
        timeAgo: "3 days ago",
        image: "/homepage/community1.png",
        description:
            "Who knew glamping could be this luxurious? Waking up to the sounds of the savanna is something I'll never forget. ✨",
        likes: 2100,
        comments: 56,
        shares: 34,
    },
];

export const navLinks = [
    { label: "Home", href: "/", active: true },
    { label: "Marketplace", href: "/marketplace", active: false },
    { label: "My Packages", href: "/my-packages", active: false },
    { label: "My Trips", href: "/my-trips", active: false },
    { label: "Feed", href: "/feed", active: false },
];
