export interface Package {
  id: string;
  title: string;
  category: 'safari' | 'beach' | 'cultural' | 'adventure' | 'extreme';
  destination: string;
  description: string;
  price: number;
  rating: number;
  reviews: number;
  image: string;
  duration: string;
  groupSize: string;
  highlights: string[];
  includes: string[];
}

export const CATEGORIES = [
  { id: 'all', label: 'All Categories' },
  { id: 'safari', label: 'Safari' },
  { id: 'beach', label: 'Beach' },
  { id: 'cultural', label: 'Cultural' },
  { id: 'adventure', label: 'Adventure' },
  { id: 'extreme', label: 'Extreme' },
];

export const packages: Package[] = [
  {
    id: '1',
    title: 'Serengeti Safari',
    category: 'safari',
    destination: 'Tanzania',
    description: 'Experience the great migration and encounter the Big Five in their natural habitat.',
    price: 2500,
    rating: 4.9,
    reviews: 487,
    image: '/images/lion.png',
    duration: '7 days',
    groupSize: '2-8',
    highlights: ['Great Migration', 'Big Five Safari', 'Ngorongoro Crater', 'Local guides'],
    includes: ['Accommodation', 'Meals', 'Park fees', 'Game drives'],
  },
  {
    id: '2',
    title: 'Cape Town Beach Escape',
    category: 'beach',
    destination: 'South Africa',
    description: 'Relax on pristine beaches with stunning mountain views and vibrant coastal culture.',
    price: 1800,
    rating: 4.8,
    reviews: 342,
    image: '/images/capeTown.jpg',
    duration: '5 days',
    groupSize: '2-10',
    highlights: ['Table Mountain', 'Boulders Beach', 'Wine tasting', 'Sunset cruises'],
    includes: ['Accommodation', 'Breakfast', 'Tours', 'Activities'],
  },
  {
    id: '3',
    title: 'Maasai Cultural Immersion',
    category: 'cultural',
    destination: 'Kenya',
    description: 'Immerse yourself in Maasai traditions and learn about their rich heritage.',
    price: 1200,
    rating: 4.7,
    reviews: 256,
    image: '/images/masai.webp',
    duration: '4 days',
    groupSize: '2-6',
    highlights: ['Maasai villages', 'Traditional ceremonies', 'Craft workshops', 'Cultural meals'],
    includes: ['Accommodation', 'Meals', 'Local guides', 'Workshops'],
  },
  {
    id: '4',
    title: 'Victoria Falls Adventure',
    category: 'adventure',
    destination: 'Zimbabwe',
    description: 'Experience one of the world\'s most spectacular waterfalls with thrilling activities.',
    price: 1600,
    rating: 4.9,
    reviews: 198,
    image: '/images/victoiafalls.jpg',
    duration: '3 days',
    groupSize: '2-12',
    highlights: ['Waterfall tours', 'Bungee jumping', 'White water rafting', 'Local markets'],
    includes: ['Accommodation', 'All activities', 'Meals', 'Transport'],
  },
  {
    id: '5',
    title: 'Namib Desert Photography',
    category: 'extreme',
    destination: 'Namibia',
    description: 'Capture stunning desert landscapes and enjoy outdoor photography in vast sand dunes.',
    price: 2200,
    rating: 4.8,
    reviews: 167,
    image: '/images/namibDesert.jpg',
    duration: '6 days',
    groupSize: '2-8',
    highlights: ['Red dunes photography', 'Sossusvlei', 'Local insights', 'Sunset sessions'],
    includes: ['Accommodation', 'Photography guide', 'Meals', 'Equipment rental'],
  },
  {
    id: '6',
    title: 'Lake Nakuru Safari',
    category: 'safari',
    destination: 'Kenya',
    description: 'Explore flamingo-filled lakes and diverse wildlife in this compact national park.',
    price: 1500,
    rating: 4.6,
    reviews: 234,
    image: '/images/nakuru.jpg',
    duration: '3 days',
    groupSize: '2-8',
    highlights: ['Flamingos', 'Rhinos', 'Lake views', 'Bird watching'],
    includes: ['Accommodation', 'Meals', 'Park fees', 'Game drives'],
  },
  {
    id: '7',
    title: 'Zanzibar Island Bliss',
    category: 'beach',
    destination: 'Tanzania',
    description: 'Discover tropical paradise with white-sand beaches and crystal-clear waters.',
    price: 1900,
    rating: 4.9,
    reviews: 412,
    image: '/images/zanibar beach.jpeg',
    duration: '5 days',
    groupSize: '2-10',
    highlights: ['Pristine beaches', 'Stone Town', 'Coral reefs', 'Spice tours'],
    includes: ['Accommodation', 'Meals', 'Snorkeling', 'Boat tours'],
  },
  {
    id: '8',
    title: 'Rwandan Gorilla Trek',
    category: 'extreme',
    destination: 'Rwanda',
    description: 'Embark on an unforgettable journey to encounter mountain gorillas in the wild.',
    price: 3500,
    rating: 5.0,
    reviews: 156,
    image: '/images/Gorilla_National_Park_019.jpg',
    duration: '4 days',
    groupSize: '2-4',
    highlights: ['Gorilla trekking', 'Rainforest exploration', 'Local villages', 'Expert guides'],
    includes: ['Accommodation', 'Permits', 'Meals', 'Expert guides'],
  },
  {
    id: '9',
    title: 'Moroccan Atlas Adventure',
    category: 'adventure',
    destination: 'Morocco',
    description: 'Trek through stunning mountain landscapes and meet Berber communities.',
    price: 1400,
    rating: 4.7,
    reviews: 289,
    image: '/images/atlas_mount.jpg',
    duration: '5 days',
    groupSize: '2-8',
    highlights: ['Mountain trekking', 'Berber villages', 'Traditional food', 'Stargazing'],
    includes: ['Accommodation', 'Meals', 'Mountain guides', 'Transport'],
  },
  {
    id: '10',
    title: 'Cairo & Pyramids Tour',
    category: 'cultural',
    destination: 'Egypt',
    description: 'Explore ancient wonders and the rich history of Egypt\'s most iconic sites.',
    price: 1600,
    rating: 4.8,
    reviews: 523,
    image: '/images/cairoPyramid.jpg',
    duration: '4 days',
    groupSize: '2-20',
    highlights: ['Great Pyramids', 'Sphinx', 'Museums', 'Nile cruises'],
    includes: ['Accommodation', 'Meals', 'Entry fees', 'Expert guides'],
  },
  {
    id: '11',
    title: 'Okavango Delta Safari',
    category: 'safari',
    destination: 'Botswana',
    description: 'Discover the world\'s largest inland delta with pristine wildlife and waterways.',
    price: 3200,
    rating: 4.9,
    reviews: 178,
    image: '/images/okavango-delta.jpg',
    duration: '6 days',
    groupSize: '2-6',
    highlights: ['Water safaris', 'Wildlife', 'Bird watching', 'Local guides'],
    includes: ['Accommodation', 'Meals', 'Safaris', 'Mokoro trips'],
  },
  {
    id: '12',
    title: 'Seychelles Tropical Retreat',
    category: 'beach',
    destination: 'Seychelles',
    description: 'Experience paradise with luxury beaches, marine life, and island romance.',
    price: 2800,
    rating: 5.0,
    reviews: 201,
    image: '/images/North-Island-Seychelles-tropical.jpg',
    duration: '7 days',
    groupSize: '2-8',
    highlights: ['Pristine beaches', 'Snorkeling', 'Island hopping', 'Sunset dinners'],
    includes: ['Luxury accommodation', 'All meals', 'Activities', 'Private transfers'],
  },
  {
    id: '13',
    title: 'Lalibela Rock Churches',
    category: 'cultural',
    destination: 'Ethiopia',
    description: 'Explore the magnificent rock-hewn churches of Lalibela, a UNESCO World Heritage site.',
    price: 1800,
    rating: 4.9,
    reviews: 312,
    image: '/images/laibela.jpeg',
    duration: '5 days',
    groupSize: '2-12',
    highlights: ['Rock-hewn churches', 'UNESCO heritage', 'Medieval architecture', 'Religious ceremonies'],
    includes: ['Accommodation', 'Meals', 'Local guides', 'Entry fees'],
  },
  {
    id: '14',
    title: 'Namib Desert Luxury Safari',
    category: 'extreme',
    destination: 'Namibia',
    description: 'Experience the ultimate desert luxury with private dune drives and starlit camps.',
    price: 4200,
    rating: 5.0,
    reviews: 89,
    image: '/images/sunset-namib-desert-sossusvlei-namibia_134785-14752.jpg',
    duration: '8 days',
    groupSize: '2-6',
    highlights: ['Luxury desert camps', 'Private guides', 'Stargazing', 'Hot air balloon'],
    includes: ['Luxury accommodation', 'Private transfers', 'All meals', 'Premium activities'],
  },
];
